FROM python:3.10.0

WORKDIR /app/FrontEnd

COPY . /app/FrontEnd

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit","run","main.py","--server.port", "8501"]