FROM python:3.10.0

WORKDIR /app/FrontEnd
WORKDIR /app

COPY . /app/FrontEnd
COPY ./requierments.txt /app

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requierments.txt

EXPOSE 8501

CMD ["streamlit","run","main.py","--server.port", "8501"]