FROM python:3.10.0

WORKDIR /app/FrontEnd
WORKDIR /app

COPY . /app/FrontEnd
COPY ./requierments.txt /app

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN /usr/local/bin/python pip install pymongo
RUN pip install -r requierments.txt

EXPOSE 8501

CMD ["streamlit","run","/app/FrontEnd/main.py","--server.port=8501"]