version: "3.8"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: car-zone-backend
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  python:
    build: 
      context: ./DB
      dockerfile: DockerFileDB
    ports:
      - "8001:8001"
    links:
      - mongodb
  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: DockerFile
    ports:
      - 8501:8501
    container_name: car-zone-frontend
    depends_on:
      - mongodb
  
