version: "3.8"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: car-zone-backend
    networks:
      - cars-app-network

networks:
  cars-app-network:
    driver: bridge