version: "3.8"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: car-zone-backend
  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: DockerFile
    ports:
      - 8501:8501
    container_name: car-zone-frontend
  mongodb:
    image: mongo
    container_name: car-zone-db
    ports:
      - 27017:27017
